apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubecommerce
  template:
    metadata:
      labels:
        app: kubecommerce
    spec:
      containers:
      - name: kubecommerce
        image: imsparsh2001/kubemmerce:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubecommerce
spec:
  selector:
    app: kubecommerce
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
